# Generated by Django 4.0.1 on 2022-01-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmlakKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=250)),
                ('olusturulma_tarihi', models.DateField(auto_now=True)),
                ('yayinlama_tarihi', models.DateField(auto_now_add=True)),
                ('yayimla', models.BooleanField(default=False)),
                ('durumu', models.CharField(choices=[('1', 'kiralık'), ('2', 'satılık')], max_length=250)),
                ('fiyat', models.PositiveIntegerField()),
                ('metrekare', models.PositiveIntegerField()),
                ('bina_yası', models.PositiveIntegerField()),
                ('resim', models.ImageField(blank=True, null=True, upload_to='kapakresimler/evler/%Y/%m')),
                ('bina_yapım_yılı', models.DateField()),
                ('bulundugu_kat', models.IntegerField()),
                ('imar_durumu', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EmlakTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='IsitmaDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mainslider')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OdaSayisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmlakKayitFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='evler/%Y/%m')),
                ('ev_kayit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emlak.emlakkayit')),
            ],
        ),
        migrations.AddField(
            model_name='emlakkayit',
            name='emlak_tipi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emlak.emlaktipi'),
        ),
        migrations.AddField(
            model_name='emlakkayit',
            name='isitma_durumu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emlak.isitmadurumu'),
        ),
        migrations.AddField(
            model_name='emlakkayit',
            name='oda_sayısı',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emlak.odasayisi'),
        ),
    ]
