# Generated by Django 4.0.1 on 2022-01-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emlakkayit',
            name='bina_yası',
        ),
    ]
