# Generated by Django 4.0.1 on 2022-01-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0002_remove_emlakkayit_bina_yası'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emlakkayitfoto',
            name='foto',
            field=models.ImageField(upload_to='evler/%Y/%m/%d'),
        ),
    ]
