# Generated by Django 4.0.1 on 2022-01-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0003_alter_emlakkayitfoto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emlakkayit',
            name='durumu',
        ),
        migrations.AddField(
            model_name='emlakkayit',
            name='emlak_acıklamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emlakkayit',
            name='kat_sayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emlakkayit',
            name='bina_yapım_yılı',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emlakkayit',
            name='bulundugu_kat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emlakkayit',
            name='imar_durumu',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='emlakkayit',
            name='isitma_durumu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emlak.isitmadurumu'),
        ),
        migrations.AlterField(
            model_name='emlakkayit',
            name='oda_sayısı',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emlak.odasayisi'),
        ),
        migrations.AlterField(
            model_name='emlakkayit',
            name='olusturulma_tarihi',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emlakkayit',
            name='yayinlama_tarihi',
            field=models.DateField(auto_now=True),
        ),
    ]
