# Generated by Django 4.0.1 on 2022-01-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0006_rename_email_message_sender_message_cc_myself_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='cc_myself',
            field=models.BooleanField(default=False),
        ),
    ]
